apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poll-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cloud.google.com/backend-config: '{"default": "poker-backend-config"}'
spec:
  ingressClassName: gce
  tls:
  - hosts:
    - REDACTED_DOMAIN
    secretName: poker-tls
  rules:
  - host: REDACTED_DOMAIN
    http:
      paths:
      - path: /api/polls
        pathType: Prefix
        backend:
          service:
            name: poll-service
            port:
              number: 80
      - path: /api/vote
        pathType: Prefix
        backend:
          service:
            name: vote-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poker-planning-service
            port:
              number: 80
