apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poll-service
  template:
    metadata:
      labels:
        app: poll-service
    spec:
      containers:
      - name: poll-service-container
        image: mrccniv/poll-service:1.2
        ports:
        - containerPort: 3001