apiVersion: v1
kind: Service
metadata:
  name: vote-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "api-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: vote-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001